service: tti-tracker

provider:
  name: google
  runtime: nodejs8
  project: tti-tools
  credentials: ./keyfile.json
  memorySize: 1024
  timeout: 240s

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello:
    handler: trackTti
    events:
      - http: path
